title: Stackbit Fjord Theme
baseURL: /
params:
  header:
    title: David Berlin
    tagline: A generalist software engineer with a knack for product development
    bg_img: images/header-bg.jpg
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
  palette: yellow
disableKinds:
  - RSS
